name: Same step

on:
  workflow_dispatch:

jobs:
  Set-enviroment-in-same-step:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v3.0.0
        with:
          terraform_version: 1.5.7

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: |
          export TF_VAR_test="changed"
          terraform plan
